/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    GameCanvas: typeof import('./src/components/GameCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
